// Fetch action types
export const REQUEST_TOP_STORIES_IDS = 'REQUEST_TOP_STORIES_IDS';
export const REQUEST_TOP_STORIES_IDS_SUCCESS = 'REQUEST_TOP_STORIES_IDS_SUCCESS';

export const REQUEST_STORY_WITH_COMMENTS = 'REQUEST_STORY_WITH_COMMENTS';
export const REQUEST_STORY_WITH_COMMENTS_SUCCESS = 'REQUEST_STORY_WITH_COMMENTS_SUCCESS';

export const REQUEST_FAIL = 'REQUEST_FAIL';

// Story and Comments action types
export const POPULATE_STORY = 'POPULATE_STORY';
export const POPULATE_COMMENTS = 'POPULATE_COMMENTS';

export const CLEAR_STORY = 'CLEAR_STORY';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
